services:
  grpc:
    container_name: rust-grpc
    build:
      context: .
      dockerfile: ./docker/local/rust/Dockerfile
    command: cargo watch -x run
    volumes:
      - .:/app
    ports:
      - "50051:50051"
    # .env.testing利用時に上書きしたい環境変数を設定する
    environment:
      - ENV
      - GRPC_PORT
      - RUST_LOG
    tty: true
    stdin_open: true
